In [51]:
import pandas as pd
import numpy as np


In [52]:
df=pd.read_csv("spam.csv")
df 

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [53]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [54]:
def get_spam_number(x):
    if x=="spam":
        return 1
    else:
        return 0

In [55]:
df["Spam"]=df['Category'].apply(lambda x : 1 if x=="spam" else 0)

In [56]:
df['Spam']=df['Category'].apply(get_spam_number)

In [7]:
df.drop("Category",axis=1,inplace=True)


In [8]:
df 

Message  Spam
0     Go until jurong point, crazy.. Available only ...     0
1                         Ok lar... Joking wif u oni...     0
2     Free entry in 2 a wkly comp to win FA Cup fina...     1
3     U dun say so early hor... U c already then say...     0
4     Nah I don't think he goes to usf, he lives aro...     0
...                                                 ...   ...
5567  This is the 2nd time we have tried 2 contact u...     1
5568               Will ü b going to esplanade fr home?     0
5569  Pity, * was in mood for that. So...any other s...     0
5570  The guy did some bitching but I acted like i'd...     0
5571                         Rofl. Its true to its name     0

[5572 rows x 2 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['Message'],df['Spam'],test_size=0.2,random_state=23,stratify=df["Spam"])

In [10]:
X_train.shape

(4457,)

In [11]:
X_test.shape 

(1115,)

In [12]:
type(X_train)

pandas.core.series.Series

In [13]:
X_train[:4]

5345                                     Wat ü doing now?
3386                                            Ok can...
601     Mind blastin.. No more Tsunamis will occur fro...
3054                     Pls send me the correct name da.
Name: Message, dtype: object

In [14]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:4]

5345    0
3386    0
601     0
3054    0
Name: Spam, dtype: int64

In [16]:
X_train.values 

array(['Wat ü doing now?', 'Ok can...',
       'Mind blastin.. No more Tsunamis will occur from now on.. Rajnikant stopped swimming in Indian Ocean..:-D',
       ..., 'Ok u can take me shopping when u get paid =D',
       'How much r ü willing to pay?',
       'Kent vale lor... Ü wait 4 me there ar?'], dtype=object)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
c=CountVectorizer()

In [18]:
dir(c)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',
 'fit_transform',


In [19]:
x_train_cv=c.fit_transform(X_train)

In [20]:
x_train_cv.toarray()[:2][0]


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
x_train_cv.shape


(4457, 7779)

In [22]:
c.get_feature_names_out().shape

(7779,)

In [23]:
dir(c)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'decode',
 'decode_error',
 'dtype',
 'encoding',
 'fit',

In [24]:
c.vocabulary_

{'wat': 7425,
 'doing': 2415,
 'now': 4861,
 'ok': 4934,
 'can': 1651,
 'mind': 4506,
 'blastin': 1395,
 'no': 4813,
 'more': 4604,
 'tsunamis': 7090,
 'will': 7552,
 'occur': 4906,
 'from': 3042,
 'on': 4953,
 'rajnikant': 5584,
 'stopped': 6535,
 'swimming': 6693,
 'in': 3669,
 'indian': 3693,
 'ocean': 4907,
 'pls': 5283,
 'send': 6043,
 'me': 4425,
 'the': 6844,
 'correct': 2033,
 'name': 4701,
 'da': 2159,
 'great': 3254,
 'to': 6960,
 'hear': 3402,
 'you': 7741,
 'are': 1058,
 'settling': 6074,
 'well': 7484,
 'so': 6315,
 'what': 7506,
 'happenin': 3353,
 'wit': 7580,
 'ola': 4942,
 'sorry': 6360,
 'll': 4184,
 'call': 1626,
 'later': 4057,
 'text82228': 6819,
 'get': 3139,
 'ringtones': 5818,
 'logos': 4204,
 'and': 972,
 'games': 3088,
 'www': 7676,
 'txt82228': 7122,
 'com': 1925,
 'questions': 5552,
 'info': 3700,
 'co': 1894,
 'uk': 7147,
 'thts': 6909,
 'god': 3186,
 'gift': 3152,
 'for': 2963,
 'birds': 1371,
 'as': 1096,
 'humans': 3572,
 'hav': 3379,
 'some': 6326,
 'na

In [25]:
c.get_feature_names_out()[1121]

'astne'

In [26]:
c.vocabulary_

{'wat': 7425,
 'doing': 2415,
 'now': 4861,
 'ok': 4934,
 'can': 1651,
 'mind': 4506,
 'blastin': 1395,
 'no': 4813,
 'more': 4604,
 'tsunamis': 7090,
 'will': 7552,
 'occur': 4906,
 'from': 3042,
 'on': 4953,
 'rajnikant': 5584,
 'stopped': 6535,
 'swimming': 6693,
 'in': 3669,
 'indian': 3693,
 'ocean': 4907,
 'pls': 5283,
 'send': 6043,
 'me': 4425,
 'the': 6844,
 'correct': 2033,
 'name': 4701,
 'da': 2159,
 'great': 3254,
 'to': 6960,
 'hear': 3402,
 'you': 7741,
 'are': 1058,
 'settling': 6074,
 'well': 7484,
 'so': 6315,
 'what': 7506,
 'happenin': 3353,
 'wit': 7580,
 'ola': 4942,
 'sorry': 6360,
 'll': 4184,
 'call': 1626,
 'later': 4057,
 'text82228': 6819,
 'get': 3139,
 'ringtones': 5818,
 'logos': 4204,
 'and': 972,
 'games': 3088,
 'www': 7676,
 'txt82228': 7122,
 'com': 1925,
 'questions': 5552,
 'info': 3700,
 'co': 1894,
 'uk': 7147,
 'thts': 6909,
 'god': 3186,
 'gift': 3152,
 'for': 2963,
 'birds': 1371,
 'as': 1096,
 'humans': 3572,
 'hav': 3379,
 'some': 6326,
 'na

In [27]:
x_train_np  = x_train_cv.toarray()
x_train_np 

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
X_train[:4]

5345                                     Wat ü doing now?
3386                                            Ok can...
601     Mind blastin.. No more Tsunamis will occur fro...
3054                     Pls send me the correct name da.
Name: Message, dtype: object

In [30]:
np.where(x_train_np[0]!=0)

(array([2415, 4861, 7425], dtype=int64),)

In [31]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [32]:
x_test_cv=c.transform(X_test)


In [33]:
y_pred=model.predict(x_test_cv)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
from sklearn.metrics import  classification_report,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       966
           1       0.96      0.92      0.94       149

    accuracy                           0.98      1115
   macro avg       0.98      0.96      0.97      1115
weighted avg       0.98      0.98      0.98      1115



In [ ]:
print(confusion_matrix())

In [ ]:
dir(nltk)

In [42]:
from sklearn.pipeline import Pipeline

In [44]:
clf=Pipeline([("vector",CountVectorizer()),("mnb",MultinomialNB())])
clf.fit(X_train,y_train)

Pipeline(steps=[('vector', CountVectorizer()), ('mnb', MultinomialNB())])

In [46]:
y_pred=clf.predict(X_test)
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
clf.score(X_test,y_test)


0.9847533632286996

In [41]:

dir(pipeline)

['Bunch',
 'FeatureUnion',
 'FunctionTransformer',
 'NotFittedError',
 'Parallel',
 'Pipeline',
 'TransformerMixin',
 '_BaseComposition',
 '_VisualBlock',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_final_estimator_has',
 '_fit_one',
 '_fit_transform_one',
 '_name_estimators',
 '_print_elapsed_time',
 '_safe_tags',
 '_transform_one',
 'available_if',
 'check_is_fitted',
 'check_memory',
 'clone',
 'defaultdict',
 'delayed',
 'deprecated',
 'islice',
 'make_pipeline',
 'make_union',
 'np',
 'sparse']